---
concurrency:
  cancel-in-progress: true
  group: markdownlint-${{ github.ref }}
jobs:
  markdownlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          key: >-
            pip-${{ github.job }}-${{
            hashFiles('.github/workflows/markdownlint.yml') }}
          path: ~/.cache/pip
          restore-keys: |
            pip-${{ github.job }}-
      - name: Install tools
        run: |
          npm install -g markdownlint-cli
          pip install \
            assert-no-inline-directives \
            assert-no-linter-config-files
      - name: Assert no inline markdownlint disables
        run: >-
          assert-no-inline-directives
          --tools markdownlint
          --verbose
          ${{ github.workspace }}/**/*
      - name: Assert no markdownlint config files
        run: >-
          assert-no-linter-config-files
          --linters markdownlint
          --verbose
          ${{ github.workspace }}
      - name: Lint Markdown
        run: markdownlint '**/*.md'
name: Markdown Lint
on:
  pull_request:
    paths:
      - '**/*.md'
  push:
    branches: [main]
    paths:
      - '**/*.md'
  workflow_dispatch:
